apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
data:
  SECRET_KEY: "secure-production-key-for-django"
  DEBUG: "False"
  ALLOWED_HOSTS: "*.elb.amazonaws.com,*.ec2.internal,*"
  DB_ENGINE: "postgres"
  DB_NAME: "postgres"
  DB_USER: "postgres"
  DB_PASSWORD: "postgres"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  CELERY_BROKER_URL: "redis://redis:6379/0"
  CELERY_RESULT_BACKEND: "redis://redis:6379/0"
